// Copyright (C) Intel Corporation
// Licensed under the MIT License

#pragma once

#define OVEP_PLUGIN_MAJOR_VERSION 1
#define OVEP_PLUGIN_MINOR_VERSION 1
#define OVEP_PLUGIN_PATCH_VERSION 0

#define OVEP_PLUGIN_MAJOR_VERSION_STR "1"
#define OVEP_PLUGIN_MINOR_VERSION_STR "1"
#define OVEP_PLUGIN_PATCH_VERSION_STR "0-dev"

#define OVEP_PLUGIN_VERSION OVEP_PLUGIN_MAJOR_VERSION_STR "." OVEP_PLUGIN_MINOR_VERSION_STR "." OVEP_PLUGIN_PATCH_VERSION_STR
#define OVEP_PLUGIN_VER_TAGGED OVEP_PLUGIN_VERSION "+" GIT_COMMIT_ID
