name: Cleanup PIP caches
on:
  workflow_dispatch:
  schedule:
    # at 00:00 on the 1st day of every month
    - cron: '0 0 1 * *'

jobs:
  Cleanup_PIP_Caches:
    runs-on: aks-linux-2-cores-8gb
    container:
      image: openvinogithubactions.azurecr.io/dockerhub/ubuntu:20.04
      volumes:
        - /mount:/mount
    env:
      PIP_CACHE_PATH: /mount/caches/pip

    steps:
      - name: Pre-Collecting Cache Info
        run: |
          echo "Cache info: "
          du -h -d2 ${PIP_CACHE_PATH}

      - name: Cleanup cache
        run: |
          echo "Delete cache files if they have not been used in over 30 days"
          [ ! -z "${PIP_CACHE_PATH}" ] && find ${PIP_CACHE_PATH} ! -type d -atime +30 -delete

      - name: Post-Collecting Cache Info
        run: |
          echo "Cache info: "
          du -h -d2 ${PIP_CACHE_PATH}
