name: 'Dependency Review'
on: [pull_request, merge_group]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4.3.2
        with:
          config-file: './.github/dependency_review.yml'
          base-ref: ${{ github.pull_request.base.sha || github.event.merge_group.base_ref }}
          head-ref: ${{ github.pull_request.head.sha || github.ref }}
